spring.application.name=gamestore

# Configurar o banco de dados
spring.datasource.url=jdbc:postgresql://dpg-d6tvgfjuibrs73epl2bg-a.ohio-postgres.render.com/db_deploy_gs_edxzyluksz
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# OBS: Nunca colocar senhas em documentos qe vão para o github

## Configurações dp JPA - Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect